//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentStreamingSystem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public int ID { get; set; }
        public string CourseName { get; set; }
        public string Credits { get; set; }
        public string ClassType { get; set; }
        public string CourseType { get; set; }
        public Nullable<System.DateTime> BeginsAt { get; set; }
        public Nullable<System.DateTime> EndsAt { get; set; }
        public string ThemeColor { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string RoomName { get; set; }
        public string Campus { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
