//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentStreamingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int CourseID { get; set; }
        public string CourseNo { get; set; }
        public string CourseName { get; set; }
        public string Programme { get; set; }
        public string Campus { get; set; }
        public string Credits { get; set; }
        public string Streams { get; set; }
        public string ClassType { get; set; }
        public System.DateTime BeginsAt { get; set; }
        public System.DateTime EndsAt { get; set; }
    }
}
