//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentStreamingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int TutorID { get; set; }
        public string TutorName { get; set; }
        public string TutorEmailID { get; set; }
    }
}
