//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentStreamingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> APNo_StudentID { get; set; }
        public string AvailableCredits { get; set; }
        public string TotalCredits { get; set; }
        public string CourseName { get; set; }
        public Nullable<System.DateTime> BeginsAt { get; set; }
        public Nullable<System.DateTime> EndsAt_ { get; set; }
        public string Streams { get; set; }
        public string Room { get; set; }
        public string Remark { get; set; }
    }
}
